stages:
  - setup
  - lint
  - test
  - release

setup_env:
  image: registry.git.platy.bzh/platylab/pipeline/bash-runner:latest
  stage: setup
  artifacts:
    when: on_success
    access: all
    expire_in: 1h
    reports:
      dotenv: .env
  script:
    - set -xeuo pipefail
    - mise trust -a
    - mise ls --offline --current --json | jq -r 'keys[] as $k | "\($k|ascii_upcase|gsub("-"; "_"))_VERSION=\(.[$k][0] | .requested_version // .version)"' > .env
    - cat .env


.poetry-setup:
  image: "registry.git.platy.bzh/platylab/python/poetry-runner:${PYTHON_VERSION}_${POETRY_VERSION}"
  needs:
    - setup_env
  before_script:
    - poetry config virtualenvs.in-project true
    - poetry install --all-extras
    - eval "$(poetry env activate)"

tox-lint:
  extends: .poetry-setup
  stage: lint
  script:
    - tox -e lint

tox-test:
  extends: .poetry-setup
  stage: test
  script:
    - tox

poetry-publish:
  extends: .poetry-setup
  stage: release
  variables:
    POETRY_PUBLISH_REPOSITORY_NAME: pypi
    POETRY_PUBLISH_PYPI_REPO_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    POETRY_PUBLISH_USERNAME: gitlab-ci-token
    POETRY_PUBLISH_PASSWORD: ${CI_JOB_TOKEN}
  needs:
    - tox-lint
    - tox-test
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - poetry config repositories.${POETRY_PUBLISH_REPOSITORY_NAME} ${POETRY_PUBLISH_PYPI_REPO_URL}
    - poetry config http-basic.${POETRY_PUBLISH_REPOSITORY_NAME} ${POETRY_PUBLISH_USERNAME} "${POETRY_PUBLISH_PASSWORD}"
    - poetry publish --build --repository ${POETRY_PUBLISH_REPOSITORY_NAME}
