[tox]
requires =
    tox>=4.2
no_package = true

[testenv]
commands =
    poetry run pytest {posargs}
allowlist_externals =
    poetry
    pytest
log_cli = True

[testenv:lint]
skip_install = true
commands =
    poetry run pyright
    poetry run ruff check .
    poetry run ruff format --check .
allowlist_externals =
    poetry
    pyright
    ruff
