remote-control:
  control-enable: yes #1
  control-interface: 0.0.0.0 #1
  control-port: 8953 #1
  server-key-file: "/usr/local/unbound/ssl/unbound_server.key" #1
  server-cert-file: "/usr/local/unbound/ssl/unbound_server.pem" #1
  control-key-file: "/usr/local/unbound/ssl/unbound_control.key" #1
  control-cert-file: "/usr/local/unbound/ssl/unbound_control.pem" #1

forward-zone:
  name: "." #1
  forward-addr: 10.10.10.55 #1

server:
  interface: 0.0.0.0 #1
  port: 5335 #1
  prefer-ip4: yes #1
  do-ip4: yes #1
  do-ip6: no #1
  do-udp: yes #1
  do-tcp: yes #1
  access-control: 0.0.0.0/0 allow #1
  serve-expired: yes #1
  serve-expired-ttl: 0 #1
  serve-expired-client-timeout: 1800 #1
  include: "/usr/local/unbound/server.d/*.conf" #1
  local-zone: "example.com." static #1
  local-zone: "example.eu." transparent #2
  local-data: "admin.example.com. IN A 1.2.3.4" #2
  local-data: "tofu.example.eu. IN A 3.5.45.126" #3
  local-data: "text.example.com. IN A 3.5.45.126" #4
  local-data: "test.example.com. IN A 1.2.3.5" #1
  local-data: "text23.example.com. 60 IN A 3.5.45.126" #5
  local-data: "tofu.example.com. 60 IN A 3.5.45.126" #6
  local-data: "tofuuu.example.com. 60 IN A 3.5.45.126" #7
  local-data: "tofuuuuu.example.com. 60 IN A 3.5.45.126" #8
  local-data: "chocolate.example.com. 666 IN A 1.2.3.4" #9
